Repository vrom911/vrom911.github.io, pull requests merged in 2019-03, with the labels that each got.

#18 [#7] CV page
  css/about.css
  css/blog.css
  css/button.css
  css/main.css
  css/normalize.css
  css/post.css
  files/cv_Veronika_Romashkina.pdf
  images/companies/ae.png
  images/companies/atef.png
  images/companies/eug.jpg
  images/companies/hm.jpg
  images/companies/sk.png
  src/Website.hs
  src/Website/Experience.hs
  src/Website/Social.hs
  templates/about.html
  templates/default.html
  templates/footer.html
  templates/hobbies.html
  website.cabal
Labels: content

#20 [#19] Fix 404 page
  templates/404.html
Labels: bug

#21 [#11] Add metadata, put nav to context
  pde/navblock1.pde
  pde/navblock2.pde
  pde/navblock3.pde
  pde/navblock4.pde
  src/Website.hs
  src/Website/Blog.hs
  src/Website/Nav.hs
  templates/404.html
  templates/default.html
  templates/post.html
  website.cabal
Labels: enhancement, refactoring

#22 [#3] Add main page content
  css/default.css
  css/main.css
  images/me.png
  js/main.js
  pde/backgr.pjs
  pde/backgr1.pde
  templates/index.html
  templates/info.html
Labels: content, html/css etc

#23 [#8] projects page
  css/about.css
  css/main.css
  src/Website.hs
  src/Website/Project.hs
  templates/about.html
  templates/index.html
  templates/projects.html
  website.cabal
Labels: content, html/css etc

#24 [#12] Add analytics
  templates/default.html
  templates/post.html
  website.cabal
Labels: enhancement, meta

#25 [#10] Add website blog post
  blog/2019-02-14-this-site.md
  blog/2019-03-06-website-is-not-easy.md
  css/post.css
  src/Website/Blog.hs
  templates/projects.html
  website.cabal
Labels: content, enhancement

#26 Fixed closing tag mismatch
  blog/2019-03-06-website-is-not-easy.md
Labels: bug, content

#28 [#27] Add Indonesia
  templates/hobbies/travel.html
Labels: map

#30 [#29] Match files dir
  src/Website.hs
Labels: hakyll

#31 Add lenses blog post
  blog/2019-03-20-write-yourself-a-lens.md
  css/post.css
Labels: blog post
